/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataEngine.Array;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmad Riza
 */
public class Edit extends javax.swing.JFrame {

    private final int COL_NIM = 0;
    private final int COL_NAMA = 1;
    private final int COL_ANGKATA = 2;
    private final int COL_JK = 3;
    private final int COL_HP = 4;
    private final int COL_SKILL = 5;

    private String where;
    private int by;

    private String NIM;
    private String Nama;
    private char JK;
    private int Angkatan;
    private String HP;
    private String Skills = "";
    private Array arrayHandler;
    private String[] searchRes;

    /**
     * Creates new form Add
     */
    public Edit() {
        initComponents();
        setEnable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        if (!MainUI.empty) {
            this.arrayHandler = new Array();
            arrayHandler.insert(MainUI.db.getResult("NIM", "ASC"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAngkatan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        chkJava = new javax.swing.JCheckBox();
        chkPhp = new javax.swing.JCheckBox();
        chkCPP = new javax.swing.JCheckBox();
        chkCSub = new javax.swing.JCheckBox();
        chkHtmlCSS = new javax.swing.JCheckBox();
        chkPhyton = new javax.swing.JCheckBox();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        comboJK = new javax.swing.JComboBox<>();
        txtWhere = new javax.swing.JTextField();
        optBy = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnFind = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Mahasiswa");
        setResizable(false);

        jLabel3.setText("NIM :");

        jLabel4.setText("NAMA :");

        jLabel5.setText("ANGKATAN :");

        txtNIM.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtNama.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtAngkatan.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("NO. HP :");

        jLabel7.setText("SKILL :");

        chkJava.setText("java");

        chkPhp.setText("php");

        chkCPP.setText("C++");

        chkCSub.setText("C#");

        chkHtmlCSS.setText("Html&CSS");

        chkPhyton.setText("Phyton");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel8.setText("JENIS KELAMIN :");

        comboJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        txtWhere.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWhereKeyPressed(evt);
            }
        });

        optBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIM", "Nama" }));
        optBy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                optByKeyPressed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtWhere, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optBy, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkJava)
                            .addComponent(chkCPP)
                            .addComponent(chkHtmlCSS))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkPhyton)
                            .addComponent(chkCSub)
                            .addComponent(chkPhp))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNama)
                            .addComponent(txtNIM)
                            .addComponent(txtAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboJK, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWhere, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(optBy, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chkJava)
                    .addComponent(chkPhp))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCPP)
                    .addComponent(chkCSub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHtmlCSS)
                    .addComponent(chkPhyton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateVar() {
        this.where = txtWhere.getText().trim().toLowerCase();
        this.by = optBy.getSelectedIndex();
    }

    /**
     * FALIDASI STRING KE INTEGER
     *
     * @param STRING TEXT YANG AKAN DIVALIDASI
     * @return BOOLEAN HASIL
     */
    private boolean checkInt(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException e) {
            System.out.println("NOT NUMBER!");
        }
        return false;
    }
    //end
    /**
     * VALIDASI NO. HP
     * @param STRING NO HP
     * @return BOOLEAN HASIL
     */
    private boolean hpValidate(String s) {

        try {
            if (s.charAt(0) == '+') {
                Integer.parseInt(s.substring(1, s.length() / 2));
            } else {
                Integer.parseInt(s.substring(0, s.length() / 2));
            }
            Integer.parseInt(s.substring(s.length() / 2 + 1, s.length()));
            return true;
        } catch (NumberFormatException e) {
            System.out.println("NOT VALID NO. HP");
        }
        return false;
    }
    /**
     * TOMBOL UPDATE DI PENCET
     * @param evt 
     */
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //cek kosong

        if ("".equals(txtNIM.getText()) || "".equals(txtNama.getText()) || "".equals(txtAngkatan.getText())) {
            JOptionPane.showMessageDialog(null, "Semua form harus diisi!");
            return;
        }
        //cek input salah
        if (!checkInt(txtAngkatan.getText()) || !checkInt(txtNIM.getText())) {
            JOptionPane.showMessageDialog(null, "Form NIM dan Angkatan harus diisi angka!");
            return;
        }
        //validasi Hp
        if (!hpValidate(txtHP.getText())) {
            JOptionPane.showMessageDialog(null, "No. Hp tidak valid!");
            return;
        }

        this.NIM = txtNIM.getText().trim();

        if (!MainUI.empty) {
            //pencarian
            //jika ada nim sama
            String[] res = arrayHandler.find(0, NIM);
            if (res != null) {
                if (!res[COL_NIM].equals(searchRes[COL_NIM])) {
                    JOptionPane.showMessageDialog(null, "NIM sudah ada!");
                    return;
                }
            }
        }

        this.Angkatan = Integer.parseInt(txtAngkatan.getText().trim());
        txtNIM.setText("");
        txtAngkatan.setText("");
        this.Nama = txtNama.getText().trim().toUpperCase();
        txtNama.setText("");
        this.HP = txtHP.getText().trim();
        txtHP.setText("");
        this.JK = comboJK.getSelectedItem().toString().charAt(0);
        this.Skills = "";
        if (chkJava.isSelected()) {
            Skills += " java";
        }
        if (chkPhp.isSelected()) {
            Skills += " php";
        }
        if (chkCPP.isSelected()) {
            Skills += " c++";
        }
        if (chkCSub.isSelected()) {
            Skills += " c#";
        }
        if (chkHtmlCSS.isSelected()) {
            Skills += " Html+CSS";
        }
        if (chkPhyton.isSelected()) {
            Skills += " phyton";
        }
        Skills = Skills.trim();//hapus spasi

        chkJava.setSelected(false);
        chkPhp.setSelected(false);
        chkCPP.setSelected(false);
        chkCSub.setSelected(false);
        chkHtmlCSS.setSelected(false);
        chkPhyton.setSelected(false);

        MainUI.db.delete(searchRes[COL_NIM]);
        MainUI.db.insert(NIM, Nama, JK, Angkatan, HP, Skills);
        MainUI.saved = false;
        System.out.println("data updated");
        JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
        resetForm();
        setEnable(false);
    }//GEN-LAST:event_btnUpdateActionPerformed
    /**
     * SET NILAI FORM BERDASARKAN HASIL CARI
     */
    public void setForm() {
        txtNIM.setText(searchRes[COL_NIM]);
        txtNama.setText(searchRes[COL_NAMA]);
        txtHP.setText(searchRes[COL_HP]);
        txtAngkatan.setText(searchRes[COL_ANGKATA]);

        //checkbox skill setter
        String[] skills = searchRes[COL_SKILL].split(" ");
        for (int i = 0; i < skills.length; i++) {
            if (skills[i].equals("java")) {
                chkJava.setSelected(true);
            } else if (skills[i].equals("php")) {
                chkPhp.setSelected(true);
            } else if (skills[i].equals("c++")) {
                chkCPP.setSelected(true);
            } else if (skills[i].equals("c#")) {
                chkCSub.setSelected(true);
            } else if (skills[i].equals("Html+CSS")) {
                chkHtmlCSS.setSelected(true);
            } else if (skills[i].equals("phyton")) {
                chkPhyton.setSelected(true);
            }
        }
        //jk setter
        JK = searchRes[COL_JK].charAt(0);
        if (JK == 'L') {
            comboJK.setSelectedIndex(0);
        } else {
            comboJK.setSelectedIndex(1);
        }

    }
    /**
     * KOSONGIN FORM
     */
    public void resetForm() {
        txtWhere.setText("");
    }
    /**
     * HIDUP/MATIKAN FORM
     * @param cond TRUE/FALSE
     */
    public void setEnable(boolean cond) {
        if (cond) {
            txtNIM.setEnabled(true);
            txtNama.setEnabled(true);
            txtAngkatan.setEnabled(true);
            txtHP.setEnabled(true);
            chkJava.setEnabled(true);
            chkPhp.setEnabled(true);
            chkCPP.setEnabled(true);
            chkCSub.setEnabled(true);
            chkHtmlCSS.setEnabled(true);
            chkPhyton.setEnabled(true);
            comboJK.setEnabled(true);
            btnUpdate.setEnabled(true);
        } else {
            txtNIM.setEnabled(false);
            txtNama.setEnabled(false);
            txtAngkatan.setEnabled(false);
            txtHP.setEnabled(false);
            chkJava.setEnabled(false);
            chkPhp.setEnabled(false);
            chkCPP.setEnabled(false);
            chkCSub.setEnabled(false);
            chkHtmlCSS.setEnabled(false);
            chkPhyton.setEnabled(false);
            comboJK.setEnabled(false);
            btnUpdate.setEnabled(false);
        }
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        updateVar();
        if (!where.equals("")) {
            searchRes = arrayHandler.find(by, where);
            if (searchRes == null) {
                JOptionPane.showMessageDialog(null, "Kata kunci tidak ditemukan!");
                return;
            }
        } else {
            return;
        }
        setEnable(true);
        setForm();
    }//GEN-LAST:event_btnFindActionPerformed

    private void txtWhereKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWhereKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnFindActionPerformed(null);
        }
    }//GEN-LAST:event_txtWhereKeyPressed

    private void optByKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_optByKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnFindActionPerformed(null);
        }
    }//GEN-LAST:event_optByKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkCPP;
    private javax.swing.JCheckBox chkCSub;
    private javax.swing.JCheckBox chkHtmlCSS;
    private javax.swing.JCheckBox chkJava;
    private javax.swing.JCheckBox chkPhp;
    private javax.swing.JCheckBox chkPhyton;
    private javax.swing.JComboBox<String> comboJK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> optBy;
    private javax.swing.JTextField txtAngkatan;
    private javax.swing.JTextField txtHP;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtWhere;
    // End of variables declaration//GEN-END:variables
}
